server:
  port: 3009
spring:
  datasource:
    username: postgres
    password: peru2020
    url:  jdbc:postgresql://ec2-34-253-119-24.eu-west-1.compute.amazonaws.com
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
